"""Records the AIProver model's reasoning, which the harness discards.

vLLM returns a model's reasoning in the `reasoning` field of each completion;
the harness's agent (vibe) reads `reasoning_content` and drops it. This proxy
sits between the harness and the model endpoint (the SSH tunnel), forwards
every request and response unchanged, and appends the reasoning of each
chat completion to `<jobs>/<job>/s<k>/reasoning.jsonl`, the directory of the
session that made the request (read from the task message, which names it).

Start (single process):
    python3 -m aiprover_orchestration.server.reasoning_proxy --listen 18565 \\
        --upstream http://127.0.0.1:18555

A record per completion: {"turn", "time", "reasoning", "content_chars",
"tool_calls", "truncated"}, where `turn` counts the assistant messages
including this one, so it matches the turn numbers of the session transcript,
and `truncated` marks a reply stopped by the token cap.

The harness's agent sends no `max_tokens`, so a reply may run to the context
limit; a reply that does not converge then holds its session until the
session's clock. The proxy sets `max_tokens` (reasoning and answer together)
on chat requests that carry none. The default, 16,384 tokens, covers the
99.9th percentile of recorded replies (about 57,000 characters) and takes
about 9.5 min at the server's 29 tokens/s per request, below the 720 s read
timeout of the harness's HTTP client; a longer reply would be abandoned and
regenerated by the client instead of delivered. A capped reply without a tool
call ends the agent's turn; the harness's answer check then returns the Lean
errors and the session continues.

A reply capped during reasoning has neither content nor tool calls, and vLLM
rejects (400) a request whose history holds such an assistant message. The
proxy gives these messages a short placeholder content before forwarding.

vLLM rejects a request (400) whose history holds a tool call with arguments
that are not JSON or a name outside [a-zA-Z0-9_-]{1,64}. The model emits such
calls in about 1 of 100 sessions; the harness already answered them with a
tool error, but resends them, and the 400 restarts the session from scratch.
The proxy replaces such arguments with `{}` and such names, in the calls and
in the tool results that repeat them, with a sanitized form before forwarding.

With `--model`, the proxy names that served model in every request, so the
harness's configured name need not match the server's. Each chat request's
`max_tokens` is reduced, if needed, so that the prompt (counted by the
server's `/tokenize`) plus the reply fits the server's context length; a
request that exceeds it would be rejected.
"""

import argparse
import json
import logging
import re
import time
from pathlib import Path

from aiohttp import ClientSession, ClientTimeout, web

# The task message names the session's project by its absolute path,
# <work>/jobs/<job>/s<k>/proj/..., in whichever workspace runs the job.
SESSION_PATH = re.compile(r"(/[^\s\"']*/jobs/[^/\s\"']+/s\d+)/")
HOP_HEADERS = {
    "host",
    "content-length",
    "transfer-encoding",
    "connection",
    "keep-alive",
}
MAX_REPLY_TOKENS = 16384
CONTEXT_MARGIN = 64  # tokens kept free below the context length
TOOL_NAME = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")
EMPTY_REPLY = "(reply stopped at the token limit)"

logger = logging.getLogger("reasoning_proxy")


def session_of(request_body: dict) -> tuple[Path, int] | None:
    """The sample directory of a chat request and the turn it asks for."""
    messages = request_body.get("messages") or []
    for message in messages:
        match = SESSION_PATH.search(str(message.get("content") or ""))
        if match:
            directory = Path(match.group(1))
            turn = sum(m.get("role") == "assistant" for m in messages) + 1
            return directory, turn
    return None


def sanitize_tool_name(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", name)[:64] or "invalid"


def repair_tool_calls(request_body: dict) -> int:
    """Make past tool calls and their results acceptable to vLLM; return how
    many were changed."""
    repaired = 0
    for message in request_body.get("messages") or []:
        # A tool result repeats the name of the call it answers.
        name = message.get("name")
        if (
            message.get("role") == "tool"
            and isinstance(name, str)
            and not TOOL_NAME.match(name)
        ):
            message["name"] = sanitize_tool_name(name)
            repaired += 1
        for call in message.get("tool_calls") or []:
            function = call.get("function") or {}
            arguments = function.get("arguments")
            if isinstance(arguments, str):
                try:
                    json.loads(arguments)
                except json.JSONDecodeError:
                    function["arguments"] = "{}"
                    repaired += 1
            name = function.get("name")
            if isinstance(name, str) and not TOOL_NAME.match(name):
                function["name"] = sanitize_tool_name(name)
                repaired += 1
    return repaired


def fill_empty_replies(request_body: dict) -> int:
    """Give content to past assistant messages that have neither content nor
    tool calls; return how many were changed."""
    filled = 0
    for message in request_body.get("messages") or []:
        if (
            message.get("role") == "assistant"
            and not message.get("tool_calls")
            and not str(message.get("content") or "").strip()
        ):
            message["content"] = EMPTY_REPLY
            filled += 1
    return filled


def record(
    directory: Path,
    turn: int,
    reasoning: str,
    content: str,
    tool_calls: int,
    truncated: bool,
) -> None:
    if not directory.is_dir():
        return
    entry = {
        "turn": turn,
        "time": time.strftime("%H:%M:%S"),
        "reasoning": reasoning,
        "content_chars": len(content),
        "tool_calls": tool_calls,
        "truncated": truncated,
    }
    with open(directory / "reasoning.jsonl", "a") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


class Accumulator:
    """Collects reasoning and content from a streamed (SSE) completion."""

    def __init__(self):
        self.buffer = b""
        self.reasoning, self.content = [], []
        self.tool_call_ids = set()
        self.finish_reason = None

    def feed(self, chunk: bytes) -> None:
        self.buffer += chunk
        while b"\n" in self.buffer:
            line, self.buffer = self.buffer.split(b"\n", 1)
            line = line.strip()
            if not line.startswith(b"data:") or line == b"data: [DONE]":
                continue
            try:
                event = json.loads(line[5:])
            except json.JSONDecodeError:
                continue
            for choice in event.get("choices") or []:
                self.finish_reason = (
                    choice.get("finish_reason") or self.finish_reason
                )
                delta = choice.get("delta") or {}
                self.reasoning.append(
                    delta.get("reasoning")
                    or delta.get("reasoning_content")
                    or ""
                )
                self.content.append(delta.get("content") or "")
                for call in delta.get("tool_calls") or []:
                    self.tool_call_ids.add(call.get("index", call.get("id")))


async def forward(request: web.Request) -> web.StreamResponse:
    upstream = request.app["upstream"]
    body = await request.read()
    session = None
    if request.method == "POST" and request.path.endswith("/chat/completions"):
        try:
            payload = json.loads(body)
            session = session_of(payload)
            changed = repair_tool_calls(payload)
            if changed:
                logger.info(
                    f"repaired {changed} malformed tool call(s) in the history"
                )
            filled = fill_empty_replies(payload)
            if filled:
                logger.info(
                    f"filled {filled} empty assistant message(s) in the history"
                )
                changed = True
            if not (
                payload.get("max_tokens")
                or payload.get("max_completion_tokens")
            ):
                payload["max_tokens"] = request.app["max_reply_tokens"]
                changed = True
            model = request.app["model"]
            if model and payload.get("model") != model:
                payload["model"] = model
                changed = True
            changed = await fit_context(request.app, payload) or changed
            if changed:
                body = json.dumps(payload).encode()
        except (json.JSONDecodeError, AttributeError):
            session = None
    headers = {
        k: v for k, v in request.headers.items() if k.lower() not in HOP_HEADERS
    }
    client: ClientSession = request.app["client"]
    async with client.request(
        request.method, upstream + request.path_qs, data=body, headers=headers
    ) as reply:
        response = web.StreamResponse(
            status=reply.status,
            headers={
                k: v
                for k, v in reply.headers.items()
                if k.lower() not in HOP_HEADERS
            },
        )
        await response.prepare(request)
        streamed = "text/event-stream" in reply.headers.get("content-type", "")
        accumulator = Accumulator()
        whole = b""
        async for chunk in reply.content.iter_any():
            await response.write(chunk)
            if session and streamed:
                accumulator.feed(chunk)
            elif session:
                whole += chunk
        await response.write_eof()
    if session and reply.status == 200:
        directory, turn = session
        if streamed:
            record(
                directory,
                turn,
                "".join(accumulator.reasoning),
                "".join(accumulator.content),
                len(accumulator.tool_call_ids),
                accumulator.finish_reason == "length",
            )
        else:
            try:
                choice = json.loads(whole)["choices"][0]
                message = choice["message"]
                record(
                    directory,
                    turn,
                    message.get("reasoning")
                    or message.get("reasoning_content")
                    or "",
                    message.get("content") or "",
                    len(message.get("tool_calls") or []),
                    choice.get("finish_reason") == "length",
                )
            except (json.JSONDecodeError, KeyError, IndexError):
                pass
    return response


async def fit_context(app: web.Application, payload: dict) -> bool:
    """Reduce max_tokens so that prompt and reply fit the context length."""
    limit = app["max_model_len"]
    key = "max_tokens" if payload.get("max_tokens") else "max_completion_tokens"
    if not limit or not payload.get(key):
        return False
    query = {
        "model": payload.get("model"),
        "messages": payload.get("messages") or [],
        "add_generation_prompt": True,
    }
    if payload.get("tools"):
        query["tools"] = payload["tools"]
    try:
        async with app["client"].post(
            app["upstream"] + "/tokenize", json=query
        ) as reply:
            prompt_tokens = (await reply.json())["count"]
    except Exception:  # Counting is best effort; the request goes as it is.
        return False
    room = limit - prompt_tokens - CONTEXT_MARGIN
    if payload[key] <= room:
        return False
    payload[key] = max(room, 1)
    logger.info(
        f"max_tokens reduced to {payload[key]} ({prompt_tokens} prompt tokens)"
    )
    return True


async def start(app: web.Application) -> None:
    # Model turns can take many minutes; no total timeout.
    app["client"] = ClientSession(
        timeout=ClientTimeout(total=None, sock_connect=30)
    )
    app["max_model_len"] = None
    try:
        async with app["client"].get(app["upstream"] + "/v1/models") as reply:
            models = (await reply.json())["data"]
        served = next((m for m in models if m["id"] == app["model"]), models[0])
        app["max_model_len"] = served.get("max_model_len")
        logger.info(
            f"upstream serves {served['id']}, context {app['max_model_len']}"
        )
    except Exception as error:
        logger.warning(
            f"upstream context length unknown ({error}); not enforced"
        )


async def stop(app: web.Application) -> None:
    await app["client"].close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--listen", type=int, default=18565)
    parser.add_argument("--upstream", default="http://127.0.0.1:18555")
    parser.add_argument(
        "--max-reply-tokens",
        type=int,
        default=MAX_REPLY_TOKENS,
        help="max_tokens set on chat requests that carry none",
    )
    parser.add_argument(
        "--model",
        default="",
        help="served model name to set in every request (default: unchanged)",
    )
    arguments = parser.parse_args()
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    app = web.Application(client_max_size=256 * 1024**2)
    app["upstream"] = arguments.upstream.rstrip("/")
    app["max_reply_tokens"] = arguments.max_reply_tokens
    app["model"] = arguments.model
    app.on_startup.append(start)
    app.on_cleanup.append(stop)
    app.router.add_route("*", "/{tail:.*}", forward)
    web.run_app(app, host="127.0.0.1", port=arguments.listen, access_log=None)


if __name__ == "__main__":
    main()
